### PR TITLE
Allow PATCH requests for CodeRuns

### LINKED ISSUE #40: Enable patch on the Code Run table
We want to register a code run at the beginning of a run, but add the input and output components to it at the end..

### PR DESCRIPTION
**Pull request by nathan-cummings-ukaea**
closes #40 

@soniamitchell could you check to see if this works for you?

### CODE REVIEW

**Comment by soniamitchell** [comment]
I'm on the case 👍

**Comment by soniamitchell** [comment]
Sorry, I'm still getting 
```
$detail
[1] "Method \"PATCH\" not allowed."
```

**Comment by richardreeve** [comment]
Although this got merged, did it actually fix the problem @nathan-cummings-ukaea? It sounds from @soniamitchell's comment that it's still not possible to patch code runs...

**Comment by soniamitchell** [comment]
Ahh, sorry.. @nathan-cummings-ukaea spoke to me directly on Zulip. Turns out I was on the wrong branch and it's working fine 👍

**Pull request merged**
