### PR TITLE
Schema changes

### PR DESCRIPTION
**Pull request by alahiff**
Ignore the external object changes at the beginning (`external_object` --> `external_objects`), that's a bug fix.

### CODE REVIEW

**Review by richardreeve — APPROVED** [review]
I obviously don't fully understand how to construct this tables in python, but this looks good to me!

**Comment by richardreeve** [comment]
@nathan-cummings-ukaea Does it matter that the CI is failing? If not, this all looks good to merge to me.

**Comment by nathan-cummings-ukaea** [comment]
No I don't think that is a problem. Andrew and I tested ourselves.

**Comment by richardreeve** [comment]
@nathan-cummings-ukaea I was just having another look here, and it occurred to me that I think we agreed that each external object would have an official data product associated with it, so that it had a namespace as it's source now that we have taken the source entry away. I can't see an entry in the external object table for that though I don't think?

**Comment by nathan-cummings-ukaea** [comment]
Hmmm yeah ok I see it has an Object but not a DataProduct.

**Comment by richardreeve** [comment]
If it has a data product entry that uniquely identifies it, then maybe it also doesn't need a version too, because that is in the data product table, and the uniqueness constraint will be `doi_or_unique_name`, `title` and `data_product`?

**Comment by richardreeve** [comment]
It may not need the object entry in fact, because the data product will have the reference to the object itself.

**Comment by nathan-cummings-ukaea** [comment]
Sounds like a simple change from 'Object' --> 'DataProduct' in models.py then (as well as in the template). @alahiff , does this sound right? If so I can do that today.

**Comment by alahiff** [comment]
The CI is failing due to the author-organisation changes - I need to update the tests.

**Comment by alahiff** [comment]
@nathan-cummings-ukaea Where do you want to change `Object` --> `DataProduct`? A `DataProduct` has an associated `Object`, which then has associated `ExternalObject`s. So an `ExternalObject` is connected to a `DataProduct`, just not directly.

**Comment by nathan-cummings-ukaea** [comment]
So the issue is that there is no Namespace associated with ExternalObject right now, is that correct?

**Comment by alahiff** [comment]
If an `ExternalObject` has an associated `DataProduct` then it indirectly has a `Namespace`.

**Comment by nathan-cummings-ukaea** [comment]
So no more changes needed for that?

**Comment by alahiff** [comment]
One possible issue - what if an `ExternalObject` doesn't have a `DataProduct`? In this case there's no `Namespace`. I'm not sure if that's a problem or not.

**Comment by soniamitchell** [comment]
All `ExternalObject`s should have a `DataProduct` entry. I assumed this linkage would be done via the Data Pipeline API though, where both the `DataProduct` and `ExternalObject` were attached to the same `Object`. Unless there's a more elegant way?

**Pull request merged**
